# Generated by Django 3.2.3 on 2021-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='athlete_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('bdate', models.CharField(max_length=20)),
            ],
        ),
    ]
