# Generated by Django 3.2.3 on 2021-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=14)),
                ('msg', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='athlete_reg',
        ),
    ]
