# Generated by Django 3.2.3 on 2021-06-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_msg_contacts_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='message',
            new_name='textmsg',
        ),
    ]
